repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-format
        args: []
      - id: ruff-check
        args: [--extend-select, I, --fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        additional_dependencies: [pydantic>=2.12.5, pandas>=3.0.0, types-requests]
